version: "3.9"

services:
  db:
    image: postgres:13.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bagheera_dev
    ports:
      - "5432:5432"
